BEGIN;
CREATE TABLE public.categories
(
	category_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	category    varchar(150) NOT NULL
);

CREATE TABLE public.traders
(
	trader_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	trader      varchar(50) NOT NULL,
	image_url   varchar(250) NOT NULL
);

CREATE TABLE public.items
(
	item_id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	item 		    	varchar(150) NOT NULL,
	category_id		int NOT NULL,
	image_name		varchar(150) NOT NULL,
	wikipage_id		int NOT NULL,
	slots		    	smallint NOT NULL,
	slots_height	smallint NOT NULL,
	slots_width		smallint NOT NULL,
	image_url	  	varchar(250) NOT NULL,
  CONSTRAINT "FK_items_category_id" FOREIGN KEY ( category_id ) REFERENCES categories ( category_id )
);
CREATE INDEX "FK_IDX_items_category_id" ON items ( category_id );

CREATE TABLE public.prices
(
  timestamped timestamptz NOT NULL,
  price       integer NOT NULL,
  item_id     int NOT NULL,
  CONSTRAINT "FK_prices_item_id" FOREIGN KEY ( item_id ) REFERENCES items ( item_id )
);
CREATE INDEX ON prices (item_id, timestamped DESC);

CREATE TABLE public.trades
(
  trade_id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	trader_id 		  int NOT NULL,
	trader_loyalty	smallint NOT NULL,
  CONSTRAINT "FK_trades_trader_id" FOREIGN KEY ( trader_id ) REFERENCES traders ( trader_id )
);
CREATE INDEX "FK_IDX_trades_trader_id" ON trades ( trader_id );


CREATE TABLE public.trades_items 
(
  item_id   int REFERENCES items ( item_id ) ON UPDATE CASCADE,
  trade_id  int REFERENCES trades ( trade_id ) ON UPDATE CASCADE ON DELETE CASCADE,
  amount    int NOT NULL DEFAULT 1,
  direction varchar(50) NOT NULL,
  CONSTRAINT "PK_trades_items" PRIMARY KEY ( item_id, trade_id )
);

SELECT create_hypertable('prices', 'timestamped');

COMMIT;